### ISSUE TITLE
Manage of user_home "/var/lib/pulp" clashes with dependency in Katello

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-pulpcore#17]
The puppet-katello module defines /var/lib/pulp (https://github.com/theforeman/puppet-katello/blob/master/manifests/pulp.pp#L88) which clashes with the management of this directory here (https://github.com/theforeman/puppet-pulpcore/blob/master/manifests/config.pp#L16).

**Comment by ehelms** [comment]
Solving the clash here -- https://github.com/theforeman/puppet-katello/pull/310

**Comment by wbclark** [comment]
Closing this since theforeman/puppet-katello#310 was merged.
