### ISSUE TITLE
The 'rq' command is located at /usr/bin

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-pulpcore#19]
The current service file (https://github.com/theforeman/puppet-pulpcore/blob/master/templates/pulpcore-worker%40.service.erb#L15) attempts to call rq at a path that is different than what is packaged. The `python3-rq` package puts `rq` at `/bin/rq`.

```
[root@centos7-pulpcore modules]# yum list installed | grep rq
irqbalance.x86_64                        3:1.0.7-11.el7         @anaconda       
python3-rq.noarch                        1.1.0-1.el7            @pulpcore       
[root@centos7-pulpcore modules]# which rq
/bin/rq
```

**Comment by ekohl** [comment]
I'm guessing the real location is `/usr/bin`. However, this will only be relevant when https://github.com/theforeman/puppet-pulpcore/issues/9 is implemented.
