### ISSUE TITLE
Add database migration command 

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-pulpcore#23]

**Comment by ekohl** [comment]
There is one, but it's only when it's refreshed. This is only when the package changes or the config changes. We need a way to figure out how to determine if it needs to run:
https://github.com/theforeman/puppet-pulpcore/blob/f96b33b094870be815116dc6227b28b625efa149/manifests/database.pp#L28

**Comment by ehelms** [comment]
Looks like this should do it:

```
[root@centos7-pulpcore pulp]# django-admin migrate --plan
Planned operations:
  No planned migration operations.
```
