### ISSUE TITLE
pulpcore will not install on RHEL 8

### ISSUE THREAD

**Issue by coreone** [theforeman/puppet-pulpcore#294]
I have been trying to get this module (version 8.2.0, pulpcore version 3.22) to install on a RHEL 8 system with Foreman. Everything looks to be setup correctly (repo, dnf module), but it continually says it cannot install package `pulpcore`. I looked at the Yum repo and there is indeed no package named `pulpcore`:

https://yum.theforeman.org/pulpcore/3.22/el8/x86_64/

However, when I look at modules on my RHEL 8 machine I notice that the pulpcore module does not have an `installer` profile, unlike `foreman` which does:

```sh
# dnf module list foreman
Updating Subscription Management repositories.
Name                       Stream                     Profiles                     Summary
foreman                    el8 [e]                    installer                    Foreman module

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled

# dnf module list pulpcore
Updating Subscription Management repositories.
Last metadata expiration check: 0:00:12 ago on Thu 29 Jun 2023 09:49:30 AM EDT.
Pulpcore 3.22
Name                        Stream                     Profiles                   Summary
pulpcore                    el8 [e]                                               Pulpcore module

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
```

When I check the `modules.yaml` file in the foreman and pulpcore yum repos, I see that the pulpcore file is missing the following stanza (from the foreman repo):

```yaml
  profiles:
    installer:
      rpms:
      - foreman-installer
```

I'm very new to modules, so I don't know if that's the issue. I think that if something similar to the following existed in the pulpcore `modules.yaml` in the repo the module would start working:

```yaml
  profiles:
    installer:
      rpms:
      - python39-pulpcore
```

**Comment by ekohl** [comment]
Can you share how you use the module and the exact error? We don't have a `pulpcore` package, but `pythonXY-pulpcore` has a `Provides:`. You should be able to find it with `dnf repoquery --whatprovides pulpcore`.

**Comment by coreone** [comment]
I tested a little more today and found that it is correct that `dnf install pulpcore` as well as `dnf repoquery` do in fact find the package. The problem appears to be in `dnf list` when Puppet attempts to install that package by name:

```sh
Error: Execution of '/usr/bin/dnf -d 0 -e 1 -y list pulpcore' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Pulpcore::Install/Package[pulpcore]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/dnf -d 0 -e 1 -y list pulpcore' returned 1: Error: No matching Packages to list
```

I am currently using the module on a host where I'm building a Foreman system. The only pulp-specific configs I have are as follows:

```yaml
pulpcore::django_secret_key: <redacted>
pulpcore::postgresql_db_password: <redacted>
pulpcore::repo::version: '3.22'
```

I am including the following classes in the profile for this node:

```puppet
include pulpcore
include pulpcore::repo
```

**Comment by coreone** [comment]
We are currently on Puppet 6.

**Comment by coreone** [comment]
Tested this again using the Puppet 7 agent, same error

**Comment by coreone** [comment]
Just to check in again, this looks to be squarely a `dnf` or Puppet bug. `dnf list`, which puppet uses as a check before installation, seems to behave differently than all other `dnf` commands in how it searches for packages. For example, `dnf whatprovides` is another way to show that the resolution **should** work:

```text
# dnf whatprovides pulpcore
Updating Subscription Management repositories.
Last metadata expiration check: 0:05:05 ago on Fri 04 Aug 2023 10:20:02 AM EDT.
python39-pulpcore-3.22.2-4.el8.noarch : Pulp Django Application and Related Modules
Repo        : pulpcore
Matched from:
Provide    : pulpcore = 3.22.2

python39-pulpcore-3.22.7-1.el8.noarch : Pulp Django Application and Related Modules
Repo        : pulpcore
Matched from:
Provide    : pulpcore = 3.22.7

python39-pulpcore-3.22.9-1.el8.noarch : Pulp Django Application and Related Modules
Repo        : pulpcore
Matched from:
Provide    : pulpcore = 3.22.9
```

It could be that Puppet shouldn't be doing `dnf list` anymore, but that doesn't help to fix this current issue. I'm not sure if adding `python39-pulpcore` in the `modules.yaml` as suggested before would circumvent this issue, but I'm just going to manually install the package for now just to get past this blocker.

**Comment by ekohl** [comment]
If you run Puppet in debug mode then it tells you exactly which commands it's executing. That should be helpful in determining what it's doing.

**Comment by coreone** [comment]
As I said in the previous post:

```text
Debug: Executing: '/usr/bin/rpm -q pulpcore --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n'
Debug: Executing: '/usr/bin/dnf -d 0 -e 1 -y list pulpcore'
Error: Execution of '/usr/bin/dnf -d 0 -e 1 -y list pulpcore' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Pulpcore::Install/Package[pulpcore]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/dnf -d 0 -e 1 -y list pulpcore' returned 1: Error: No matching Packages to list
Debug: Class[Pulpcore::Install]: Resource is being skipped, unscheduling all events
```

**Comment by ekohl** [comment]
From my CentOS Stream 8 machine:
```
  Debug: Prefetching dnf resources for package
  Debug: Executing: '/usr/bin/rpm --version'
  Debug: Executing '/usr/bin/rpm -qa --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n' | sort'
  Debug: Executing: '/usr/bin/rpm -q pulpcore --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n'
  Debug: Executing: '/usr/bin/rpm -q pulpcore --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n --whatprovides'
```

So this feels like a Puppet bug. Looking at the source it must be this function, given it's the only place that has `--whatprovides`:
https://github.com/puppetlabs/puppet/blob/fc701830718de73494d22b44fecc6590040e6c41/lib/puppet/provider/package/rpm.rb#L75-L102

The specific bits were changed in https://github.com/puppetlabs/puppet/commit/62e9e43143fd7cdad142acf6f55bd21be5115fd0 so that's very old (2014), making it safe to assume it's there.

Seeing how it does call `rpm -q` but doesn't call it with `--whatprovides` it implies `@resource.allow_virtual?` is false.

We can see it's default true: https://github.com/puppetlabs/puppet/blob/fc701830718de73494d22b44fecc6590040e6c41/lib/puppet/type/package.rb#L583-L594

So the only thing I can think of is that you have something in your `site.pp` that sets it at the top level as a resource default like:
```puppet
Package {
  allow_virtual => false,
}
```

**Comment by coreone** [comment]
That was 100% the problem! Thank you! I didn't even know that setting existed in our repo before grep'ing through the whole thing. Everything installed as expected now.

Thanks again!f
