### ISSUE TITLE
Secret key handling

### ISSUE THREAD

**Issue by ekohl** [theforeman/puppet-pulpcore#31]
We need to generate a secure key:
https://github.com/theforeman/puppet-pulpcore/blob/fc9d5d05bf39d0f05713aca8500f6ad960f13c0b/templates/settings.py.erb#L5

**Comment by wbclark** [comment]
For this issue, can I use a similar approach to what we are taking at https://github.com/theforeman/puppet-pulpcore/blob/fc9d5d05bf39d0f05713aca8500f6ad960f13c0b/manifests/init.pp#L57 ?
