### ISSUE TITLE
Update to use django-admin solution for pulpcore

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-pulpcore#39]
The `django-admin` from python3-django will likely be renamed or put somewhere different.

**Comment by wbclark** [comment]
With https://github.com/theforeman/puppet-pulpcore/pull/43 merged we now have a common wrapper for all `django-admin` commands. When it is updated in the RPMs, it will only require a single update to the `admin.pp` module here.

**Comment by ekohl** [comment]
There's actually 2:
https://github.com/theforeman/puppet-pulpcore/blob/f4f177c601d63c22fd0e2fbb992a9b327cc5dbe1/manifests/admin.pp#L29
https://github.com/theforeman/puppet-pulpcore/blob/f4f177c601d63c22fd0e2fbb992a9b327cc5dbe1/manifests/database.pp#L12
