### ISSUE TITLE
Deploy Apache configurations to Foreman vhost

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-pulpcore#5]

**Comment by wbclark** [comment]
With https://github.com/theforeman/puppet-foreman_proxy_content/pull/222 we should be good to go for now, although there is some conversation about moving this to `puppet-katello` in the future.

**Comment by wbclark** [comment]
Closing this since https://github.com/theforeman/puppet-foreman_proxy_content/pull/222 was merged.
