### ISSUE TITLE
configurable REMOTE_USER_ENVIRON_NAME

### ISSUE THREAD

**Issue by wbclark** [theforeman/puppet-pulpcore#58]
> Fixes #28654

It would be even better if this is a parameter the calling module sets the right parameter to configure it. The reason for that is that now the vhost we deploy by default is insecure since every HTTP client can pass the REMOTE_USER header

_Originally posted by @ekohl in https://github.com/theforeman/puppet-pulpcore/pull/56#issuecomment-574419934_

**Comment by wbclark** [comment]
Make the REMOTE_USER_ENVIRON_NAME configurable by the module calling puppet-pulpcore.

**Comment by ekohl** [comment]
For reference, you can use `Fixes GH-58` in the PR body to automatically close issues when merging a PR.
