### ISSUE TITLE
package installation in plugin.pp should be option

### ISSUE THREAD

**Issue by wbclark** [theforeman/puppet-pulpcore#59]
In https://github.com/theforeman/puppet-pulpcore/pull/57 we saw the need to have plugins which can modify configuration without installation an additional package. Before we can implement such a plugin we need to put the `package` declaration in plugin.pp behind a new parameter, `$install_package`.

**Comment by ekohl** [comment]
We have https://github.com/theforeman/puppet-pulpcore/blob/master/manifests/plugin.pp#L9. If you have an example where you want to drop a config file but there's no migration then I'd say just using a `concat::fragment` is better.

**Comment by wbclark** [comment]
So, the source of the disconnect here was that I didn't realize there will be an RPM package for the migration. Given that there will be, it shouldn't be necessary to optionally disable the package install logic in plugins at this time. I'll close this issue.
