### ISSUE TITLE
Allow using Redis configured by Foreman

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-pulpcore#7]

**Comment by ekohl** [comment]
I'd argue this is already done. We include the common Redis:

https://github.com/theforeman/puppet-pulpcore/blob/696e8f9fa1aa997c42878683f5595955dd9be2a6/manifests/database.pp#L32

Then we configure Pulp to use a specific database:
https://github.com/theforeman/puppet-pulpcore/blob/696e8f9fa1aa997c42878683f5595955dd9be2a6/templates/settings.py.erb#L19

It should become configurable though.
